{% set name = "skorch" %}
{% set version = "0.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9910f97339e654c8d38e0075d87b735e69e5eb11db59c527fb36705b30c8d0a4

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.5
    - pip
    - setuptools
  run:
    - python >=3.5
    - numpy >=1.13.3
    - scikit-learn >=0.19.1
    - scipy >=1.1.0
    - tabulate >=0.7.7
    - tqdm >=4.14.0

test:
  imports:
    - numpy

about:
  home: https://github.com/dnouri/skorch
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A scikit-learn compatible neural network library that wraps pytorch
  doc_url: https://skorch.readthedocs.io/en/latest/
  dev_url: https://github.com/dnouri/skorch

extra:
  recipe-maintainers:
    - dhirschfeld
